Instagram/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url
from authentication.views import *
from photos.views import *
from chat.views import *
from django.conf.urls.static import static
from Instagram import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    url('error', error),
    path('photos/post', post_view),
    path('photos/likes/<post_id>', view_likes),
    path('photos/like', like_view),
    path('photos/comment', comment_view),
    path('photos/feed', feed_view),
    path('photos/<email>', profile_view),
    path('photos/tag/<tag_name>', tag_view),
    path('chat', InboxView.as_view()),
    re_path(r"chat/(?P<username>[\w.@+-]+)/", ThreadView.as_view()),
    path('register/', user_signup),
    path('logout/', logout),
    path('', user_login),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q

from authentication.models import *

class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qs = self.get_queryset().filter(qlookup).distinct()
        return qs

    def get_or_new(self, user, other_user):  # get_or_create
        username = user.email_address
        if username == other_user:
            return None, False
        qlookup1 = Q(first__email_address=username) & Q(second__email_address=other_user)
        qlookup2 = Q(first__email_address=other_user) & Q(second__email_address=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()

        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            user2 = UserModel.objects.filter(email_address=other_user).first()
            if user2 == None:
                return None, False
            if user != user2:
                obj = self.model(
                        first=user,
                        second=user2
                    )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(UserModel, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
from django.http import Http404, HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import render
from django.views.generic.edit import FormMixin
from django.contrib import messages
from django.views.generic import DetailView, ListView
from authentication.views import get_user
from .forms import ComposeForm
from .models import Thread, ChatMessage

class InboxView(ListView):
    template_name = 'inbox.html'

    def get_queryset(self):
        if get_user(self.request) is not None:
            user = get_user(self.request)
            return Thread.objects.by_user(user)
        return None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        if get_user(self.request) is not None:
            curUser = get_user(self.request)
            context['curUser'] = curUser.email_address
        return context

    def dispatch(self, request, *args, **kwargs):
        if get_user(request) is None:
            messages.error(request, 'Please log in first to access Inbox.')
            return HttpResponseRedirect('/')
        else:
            return super(InboxView, self).dispatch(request, *args, **kwargs)


class ThreadView(FormMixin, DetailView):
    template_name = 'thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        user = None
        if get_user(self.request) is not None:
            user = get_user(self.request)
        return Thread.objects.by_user(user)

    def get_object(self):
        other_username = self.kwargs.get("username")
        if get_user(self.request) is not None:
            user = get_user(self.request)

        obj, created = Thread.objects.get_or_new(user, other_username)
        if obj is None:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()

        if get_user(self.request) is not None:
            curUser = get_user(self.request)
            context['curUser'] = curUser.email_address

        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = None

        if get_user(self.request) is not None:
            user = get_user(self.request)

        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

    def dispatch(self, request, *args, **kwargs):
        if get_user(request) is None:
            messages.error(request, 'Please log in first to access Inbox.')
            return HttpResponseRedirect('/login')
        else:
            return super(ThreadView, self).dispatch(request, *args, **kwargs)

chat/templates/css.html
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">

chat/templates/inbox.html
<h1>Chats</h1>
<ul>
    {% for thread in thread_list %}
        <li>{% if curUser != thread.first.email_address %}
            <a href="/chat/{{ thread.first.email_address }}/">{{ thread.first }}</a>{% else %}
            <a href="/chat/{{ thread.second.email_address }}/">{{ thread.second }}</a>{% endif %}</li>
    {% endfor %}
</ul>

chat/templates/js.html
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
        src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>

chat/templates/thread.html
{% block content %}
    <h3>Talking to
        {% if curUser != object.first.email_address %}{{ object.first }}{% else %}{{ object.second }}{% endif %}</h3>
    <ul id='chat-items'>
        {% for chat in object.chatmessage_set.all %}
            {% if curUser == chat.user.email_address %}

                <div class="container">
                    <p>{{ chat.message }} </p>
                    <span class="time-right text-body">{{ chat.user }}</span>
                </div>

            {% else %}

                <div class="container darker">
                    <p>{{ chat.message }}</p>
                    <span class="time-left text-body">{{ chat.user }}</span>
                </div>

            {% endif %}
        {% endfor %}
    </ul>

    <form id='form' method='POST'> {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class='btn btn-primary'/>
    </form>

{% endblock %}

{% block script %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

    <script>
        $('html,body').animate({scrollTop: document.body.scrollHeight}, "fast");

        var curUser = "{{curUser}}";
        var wsStart = "ws://" + window.location.host + window.location.pathname;
        var socket = new ReconnectingWebSocket(wsStart);

        var formData = $("#form");
        var msgInput = $("#id_message");
        var chatHolder = $("#chat-items");

        socket.onmessage = function (e) {
            console.log("message", e);
            var chatDataMsg = JSON.parse(e.data);
            if (curUser == chatDataMsg.email_address) {
                chatHolder.append('<div class="container"> <p>' + chatDataMsg.message + '</p> <span class="time-right text-body">' + chatDataMsg.username + '</span> </div>')
            }
            else {
                chatHolder.append('<div class="container darker"> <p>' + chatDataMsg.message + '</p> <span class="time-left text-body">' + chatDataMsg.username + '</span> </div>')

            }
            $('html,body').animate({scrollTop: document.body.scrollHeight}, "fast");
        };

        socket.onopen = function (e) {
            console.log("Open", e);
            formData.submit(function (event) {
                event.preventDefault();
                var msgText = msgInput.val();

                var finalData = {
                    'message': msgText
                };

                socket.send(JSON.stringify(finalData));
                msgInput.val('');
            })
        };

        socket.onerror = function (e) {
            console.log("message", e)
        };

        socket.onclose = function (e) {
            console.log("message", e)
        };
    </script>
{% endblock %}